### ISSUE TITLE
Blog: At your service for more than just appcache

### ISSUE THREAD

**Issue by digitarald** [mozilla/serviceworker-cookbook#13] opened 2015-10-15 18:38 UTC
More than ~~words~~ *appcache*!  Thinking beyond offline when cooking with Service Workers.

Recipes to be defined by @lodr

**Comment by marco-c** [comment] 2015-11-04 00:07
Duplicate of #12?

**Comment by delapuente** [comment] 2015-11-04 07:24
I think so. Reopen if not.

**Comment by digitarald** [comment] 2015-11-04 17:47
This would also cover the blog post. Any takers on writing about the offline use cases?

**Comment by delapuente** [comment] 2015-11-04 17:50
Oh, perfect. I'm taking this bug. Could you give me access to Moz Hacks?

**Comment by digitarald** [comment] 2015-11-04 22:47
:tada: @delapuente! I checked with the hacks team: step 1 is draft (gdocs works great as it has comments and revisions). step 2 is scheduling a publishing date.

**Comment by marco-c** [comment] 2015-12-22 14:16
https://hacks.mozilla.org/2015/12/beyond-offline/

**Closed by marco-c** 2015-12-22 14:16 UTC
